### PR TITLE
Database schema

### PR DESCRIPTION
**Pull request by moretea**
This PR adds the endpoints for the database schema.

### CODE REVIEW

**Comment by bobvanluijt** [comment]
@moretea whoops: https://travis-ci.org/creativesoftwarefdn/weaviate/builds/427579730#L814

**Comment by moretea** [comment]
This is not ready to merge yet ;) I asked you for feedback on the APi design before, but we did this in-person last Thursday already.

**Comment by bobvanluijt** [comment]
@moretea whoops, was about to merge but not sure if you want it merged already.

Also, please use an issue to commit to ;-)
https://github.com/creativesoftwarefdn/weaviate/issues/486

**Comment by bobvanluijt** [comment]
@moretea 🎉🎉🎉

**Pull request merged**
