### PR TITLE
I added in a new header

### PR DESCRIPTION
**Pull request by carne-vore**

### CODE REVIEW

**Comment by bobvanluijt** [comment]
Thanks @carne-vore this looks great! I'll merge if all checks pass.

**Comment by bobvanluijt** [comment]
Hi @carne-vore, I noticed that the header isn't written [CamelCase](https://en.wikipedia.org/wiki/Camel_case), can you please update the PR?

**Comment by carne-vore** [comment]
@bobvanluijt done!

**Comment by bobvanluijt** [comment]
Awesome, I'll merge the PR

**Pull request closed without merging**
