### PR TITLE
gh-609: feature/p2p schema sync

### LINKED ISSUE #609: Support different schemas in P2P network
## Background 
As part of #515 and #602 we have made an over-simplification as an assumption: To get started quickly, we pretended that every instance on the network has the same schema/ontology. This enabled us to work on both the GraphQL parts (#515) as well as the Network Proxying Parts (#602) without having to build an elaborate schema synchronization system, first.

However, one of the selling points of Weaviate is that every instance in a P2P network can have a completely unique schema/ontology. This means that in turn every single node, needs to keep an up-to-date copy of every other instance's schema. Only then can we build the necessary GraphQL Fields and Objects for the particular network instances (which are very important from a UX perspective).

## Todos

* [x] make schema accessible in network pinging cycle
* [x] send hash along on each ping
* [x] consume hash in genesis and send on each update
* [x] in network figure out when a hash has changed on an update and download
  * [x] add simple diffing logic to find out which needs to be updated
  * [x] add dowloader to get schemas
  * [x] make downloader concurrent on many changes
  * [x] call in peerupdate cycle
* [x] in graphql build peer schemas based on actual schema cache of peers
* [x] docs (possibly include solving #627)
* [x] acceptance test 

## Proposal
* as part of the keep-alive pings we can include a hash of the current schema
* the Genesis instance can compare in each cycle whether the hash of any peer's schema has changed
* if so it sends out a broadcast like "instance 7 has a schema update"
* this in turn leads to all instances requesting the schema from instance 7 and caching it
* once a schema update was downloaded successfully a rebuild of the graphQL schema is triggered.

### Potential issues and limitations with this proposal
* If the broadcast request gets lost, a remote instance might never know that a schema has updated and keep an old (incorrect) version of a schema
  * could we instead of a broadcast message rely on a pull-based system instead. This way we could constantly compare desired state with actual state. If a network request gets dropped, we would simply compare the next iteration again.
* There is a short period between when the schemas across the network will not be consistent:
  * `weaviateA` updates their schema at 16:03:00
  * `weaviateA` sends the next regular keep-alive ping to the genesis at 16:03:30
  * The genesis realizes an update is necessary and sends a broadcast message at 16:03:45
  * `weaviateB` receives the broadcast and immediately downloads the new schema, finished at 16:03:55
  * If a user of `weaviateB` tries to do a `Network.Get` to `weaviateA` any time between 16:03:00 and 16:03:55 they will have an incorrect schema and the request could fail
  * I think this temporary inconsistency of schemas is OK in a P2P network, but we have to be aware of it.

Thoughts, comments, ideas on all of the above?
@moretea @bobvanluijt @idcrosby @JeroenStravers1

### LINKED ISSUE #627: Update p2p documentation
It's a bit outdated, still talks about a pure P2P approach as opposed to the Hybrid P2P approach.

Originally we wanted to update the docs as part of #602, but with #622 ongoing in parallel, this would only lead to merge conflicts en masse.

So instead, we're scoping this out from #602 and tackling it in here at some point after #622 is finished.

## Todos
* [ ] seems to be incorrect about Genesis Architecture (bootstrapping vs. hybrid p2p model)
* [ ] incorrect about how to setup a node as genesis: `environments[].P2P` does not exist anymore
* [ ] do we need some developer-facing docs somewhere about P2P architecture?

### LINKED ISSUE #642: Genesis completely untested
We don't have any way of verifying whether the genesis works as intended because

- it has no unit tests
- it has no acceptance tests
- it is not used anywhere in our setup, because for better control we must replace it with a fake in our local tests for weaviate

### PR DESCRIPTION
**Pull request by etiennedi**
**Status: ready to merge**

closes #609 
closes #627 
closes #642 

**As with the previous PR: Please do a regular merge, not a squash, so we don't lose the individual commit message and their relation to the code snippets.**

### CODE REVIEW

**Comment by bobvanluijt** [comment]
@etiennedi, please note the merge conflicts ⬆️

**Comment by etiennedi** [comment]
@bobvanjuijt Thanks for the info, there were none when I created the PR, I'll resolve them right now and ping you again.

**Comment by etiennedi** [comment]
@bobvanluijt resolved :)

**Comment by bobvanluijt** [comment]
@etiennedi W00T

**Pull request merged**
