### PR TITLE
gh-744: Feature/janus v0.3.1

### LINKED ISSUE #744: Update Janusgraph to 0.3.0
We are currently using Janusgraph v0.2.x.

## Why?
We want to (and have to) update to the latest version v.0.3.x because
* our analytics microservice (based in Java) works with the newest versions, but would need more fine tuning to work with older versions as well
* we should always aim to keep our major dependencies up to date

## Risks
We don't see any major obstacles or risks. There could be minor API changes (because the Tinkerpop version increases from 3.2 to 3.3) around the graph management queries. We hope to be able to work them out.

*Update: This turned out to be only half-true. The change in the underlying GraphSON version is a pretty massive breaking change for the API. However, we took a shortcut and downgraded to the old GraphSON version. There is a new issue to clean up this newly created tech debt: #760*

## Todos
* [x] Build new version in creativesoftwarefdn/janusgraph-docker and realease it
  * released as `:0.3.1`
* [x] Incorporate the above into our Docker setup
  * [x] dev setup
  * [x] acceptance test setup
  * [x] runtime stable setup
  * [x] runtime unstable setup 
* [x] Fix anything that doesn't work anymore
  * only minor issues due to GraphSON v1 downgrade
* [x] See if we can / have to update Elasticsearch
  * no
* ~~Update Spark, we already know that Janus 0.3 requires a newer Spark version.~~
  * spark isn't part of our regular setup yet. It will be with #719, so nothing to upgrade yet.

## Further Reading
* [Janusgraph Version Compatibility Matrix](https://docs.janusgraph.org/latest/version-compat.html)

### PR DESCRIPTION
**Pull request by etiennedi**
This upgrade janus to 0.3.1 and closes #744 

@bobvanluijt Please don't merge this yet. It is ready to be merged, but we might need to coordinate the merge as this change can be breaking for existing setups. Please message me when you have some time to tackle this.

Thanks.

### CODE REVIEW

**Comment by bobvanluijt** [comment]
Check, please let me know when to merge

**Comment by etiennedi** [comment]
> Check, please let me know when to merge

Since you are the only one currently running setups, I'd put that decision entirely in your hands. I'd highly recommend that 40ish minutes after merging this, also merge the Helm-chart one.

**Comment by etiennedi** [comment]
@bobvanluijt what's the status on this? I assume it was closed due to the branch renaming. Should I open a new PR to merge this into master instead?

**Comment by bobvanluijt** [comment]
> @bobvanluijt what's the status on this? I assume it was closed due to the branch renaming. Should I open a new PR to merge this into master instead?

Although I'm not sure, I assume this was indeed the reason for it not being here anymore. Please reopen and let me know when to merge.

**Pull request closed without merging**
